en/1-for-am-2-for-pm
en/1-yes-2-no
en/dictate/both_help
en/dictate/enter_filename
en/dictate/forhelp
en/dictate/pause
en/dictate/paused
en/dictate/playback
en/dictate/playback_mode
en/dictate/play_help
en/dictate/record
en/dictate/record_help
en/dictate/record_mode
en/dictate/truncating_audio
en/digits/0
en/digits/1
en/digits/2
en/digits/3
en/digits/4
en/digits/5
en/digits/6
en/digits/7
en/digits/8
en/digits/9
en/digits/10
en/digits/11
en/digits/12
en/digits/13
en/digits/14
en/digits/15
en/digits/16
en/digits/17
en/digits/18
en/digits/19
en/digits/20
en/digits/30
en/digits/40
en/digits/50
en/digits/60
en/digits/70
en/digits/80
en/digits/90
en/digits/a-m
en/digits/at
en/digits/billion
en/digits/day-0
en/digits/day-1
en/digits/day-2
en/digits/day-3
en/digits/day-4
en/digits/day-5
en/digits/day-6
en/digits/dollars
en/digits/h-1
en/digits/h-2
en/digits/h-3
en/digits/h-4
en/digits/h-5
en/digits/h-6
en/digits/h-7
en/digits/h-8
en/digits/h-9
en/digits/h-10
en/digits/h-11
en/digits/h-12
en/digits/h-13
en/digits/h-14
en/digits/h-15
en/digits/h-16
en/digits/h-17
en/digits/h-18
en/digits/h-19
en/digits/h-20
en/digits/h-30
en/digits/h-40
en/digits/h-50
en/digits/h-60
en/digits/h-70
en/digits/h-80
en/digits/h-90
en/digits/h-billion
en/digits/h-hundred
en/digits/h-million
en/digits/h-thousand
en/digits/hundred
en/digits/million
en/digits/minus
en/digits/mon-0
en/digits/mon-1
en/digits/mon-2
en/digits/mon-3
en/digits/mon-4
en/digits/mon-5
en/digits/mon-6
en/digits/mon-7
en/digits/mon-8
en/digits/mon-9
en/digits/mon-10
en/digits/mon-11
en/digits/oclock
en/digits/oh
en/digits/p-m
en/digits/pound
en/digits/star
en/digits/thousand
en/digits/today
en/digits/tomorrow
en/digits/yesterday
en/followme/call-from
en/followme/no-recording
en/followme/options
en/followme/pls-hold-while-try
en/followme/sorry
en/followme/status
en/ha/ac
en/ha/air-conditioner
en/ha/alarm
en/ha/amp
en/ha/amps
en/ha/attic
en/ha/baby-sleeping-mode
en/ha/back
en/ha/basement
en/ha/bathroom
en/ha/bedroom
en/ha/bright
en/ha/callerid
en/ha/carport
en/ha/closet
en/ha/coffee-pot
en/ha/cool
en/ha/cooling
en/ha/dc
en/ha/decibel
en/ha/decibels
en/ha/deck
en/ha/degree
en/ha/degrees
en/ha/den
en/ha/dim
en/ha/dining-room
en/ha/door
en/ha/doors
en/ha/down
en/ha/driveway
en/ha/dryer
en/ha/fan
en/ha/farad
en/ha/farads
en/ha/first-floor
en/ha/floor
en/ha/floors
en/ha/for-extended-status-report
en/ha/for-quick-status-report
en/ha/for-wx-report
en/ha/fountain
en/ha/foyer
en/ha/front
en/ha/furnace
en/ha/game-room
en/ha/garage
en/ha/great-room
en/ha/guest-room
en/ha/hall
en/ha/has-been-left
en/ha/heat
en/ha/heating
en/ha/heat-pump
en/ha/hot-tub
en/ha/house
en/ha/intruder
en/ha/is
en/ha/kelvin
en/ha/kitchen
en/ha/lamp
en/ha/lamps
en/ha/landscape
en/ha/laundry
en/ha/library
en/ha/light
en/ha/lights
en/ha/living-room
en/ha/locked
en/ha/locking
en/ha/mailbox
en/ha/master
en/ha/off
en/ha/office
en/ha/ohm
en/ha/ohms
en/ha/on
en/ha/open
en/ha/patio
en/ha/phone
en/ha/play
en/ha/play-room
en/ha/pool
en/ha/porch
en/ha/power-failure
en/ha/pressure
en/ha/psi
en/ha/quiet-mode
en/ha/reset
en/ha/roof
en/ha/room
en/ha/rooms
en/ha/second-floor
en/ha/secure
en/ha/security-system
en/ha/set
en/ha/side
en/ha/solar
en/ha/sprinklers
en/ha/still
en/ha/stove
en/ha/sump-pump
en/ha/sun-room
en/ha/system
en/ha/systems
en/ha/thermostat
en/ha/to-control-environ-sys
en/ha/to-control-lights-appl
en/ha/tower
en/ha/unlocked
en/ha/unlocking
en/ha/up
en/ha/volt
en/ha/volts
en/ha/washing-machine
en/ha/water-heater
en/ha/watt
en/ha/watts
en/ha/well-pump
en/ha/window
en/ha/windows
en/ha/xmas-lights
en/ha/xmas-tree
en/ha/yard
en/letters/a
en/letters/b
en/letters/c
en/letters/d
en/letters/e
en/letters/f
en/letters/g
en/letters/h
en/letters/i
en/letters/j
en/letters/k
en/letters/l
en/letters/m
en/letters/n
en/letters/o
en/letters/p
en/letters/q
en/letters/r
en/letters/s
en/letters/t
en/letters/u
en/letters/v
en/letters/w
en/letters/x
en/letters/y
en/letters/z
en/letters/ascii123
en/letters/ascii124
en/letters/ascii125
en/letters/ascii126
en/letters/ascii34
en/letters/ascii36
en/letters/ascii37
en/letters/ascii38
en/letters/ascii39
en/letters/ascii40
en/letters/ascii41
en/letters/ascii42
en/letters/ascii44
en/letters/ascii58
en/letters/ascii59
en/letters/ascii60
en/letters/ascii62
en/letters/ascii63
en/letters/ascii91
en/letters/ascii92
en/letters/ascii93
en/letters/ascii94
en/letters/ascii95
en/letters/ascii96
en/letters/asterisk
en/letters/at
en/letters/dash
en/letters/dollar
en/letters/dot
en/letters/equals
en/letters/exclaimation-point
en/letters/plus
en/letters/slash
en/letters/space
en/letters/zed
en/phonetic/9_p
en/phonetic/a_p
en/phonetic/b_p
en/phonetic/c_p
en/phonetic/d_p
en/phonetic/e_p
en/phonetic/f_p
en/phonetic/g_p
en/phonetic/h_p
en/phonetic/i_p
en/phonetic/j_p
en/phonetic/k_p
en/phonetic/l_p
en/phonetic/m_p
en/phonetic/n_p
en/phonetic/o_p
en/phonetic/p_p
en/phonetic/q_p
en/phonetic/r_p
en/phonetic/s_p
en/phonetic/t_p
en/phonetic/u_p
en/phonetic/v_p
en/phonetic/w_p
en/phonetic/x_p
en/phonetic/y_p
en/phonetic/z_p
en/silence/1
en/silence/2
en/silence/3
en/silence/4
en/silence/5
en/silence/6
en/silence/7
en/silence/8
en/silence/9
en/silence/10
en/wx/around
en/wx/barometer
en/wx/ceiling
en/wx/dew-point
en/wx/falling
en/wx/feet
en/wx/foot
en/wx/gust
en/wx/gusting-to
en/wx/gusts
en/wx/gusty
en/wx/heat-index
en/wx/humidity
en/wx/inch
en/wx/inches
en/wx/kilometer
en/wx/large
en/wx/meter
en/wx/mist
en/wx/northeast
en/wx/northwest
en/wx/percent
en/wx/point
en/wx/rising
en/wx/southeast
en/wx/southwest
en/wx/steady
en/wx/temperature
en/wx/wind-chill
en/wx/winds
en/abandon-all-hope
en/abandons
en/academic-support
en/access-code
en/access-denied
en/access-granted
en/accessible-through-system
en/account-balance-is
en/accounting
en/accounts-payable
en/accounts-receivable
en/a-charge-for-this-svc
en/a-collect-charge
en/a-collect-charge-of
en/a-connect-charge
en/a-connect-charge-of
en/activated
en/added
en/added-to
en/address
en/administration
en/advised-to-seek-shelter
en/afternoon
en/after-the-tone
en/agent-alreadyon
en/agent-incorrect
en/agent-loggedoff
en/agent-loginok
en/agent-newlocation
en/agent-pass
en/agent-user
en/airport
en/alabama
en/alaska
en/albuquerque
en/alert
en/all-circuits-busy-now
en/all-outgoing-lines-unavailable
en/all-reps-busy
en/all-your-base
en/altitude
en/ampersand
en/and
en/and-area-code
en/and-or
en/and-prs-pound-whn-finished
en/an-error-has-occured
en/an-error-has-occurred
en/another-time
en/approaching
en/approximately
en/are-you-still-there
en/are-you-still-there2
en/arizona
en/arkansas
en/arlington
en/ascending-2tone
en/astcc-account-balance-is
en/astcc-account-number-invalid
en/astcc-balance-of-account-is
en/astcc-card-number-invalid
en/astcc-digit-account-number
en/astcc-followed-by-pound
en/astcc-followed-by-the-hash-key
en/astcc-followed-by-the-pound-key
en/astcc-login12pound
en/astcc-please-enter-your
en/astcc-skipping-any-punctuation
en/asterisk-friend
en/at-any-time
en/at-customers-request
en/at-following-number
en/athletics
en/atlanta
en/atlantic
en/at-sign
en/attention-required
en/at-tone-time-exactly
en/auditing
en/austin
en/auth-incorrect
en/auth-thankyou
en/available
en/available-options
en/avg-speed-answer
en/away-naughty-boy
en/away-naughty-girl
en/backslash
en/bad
en/baltimore
en/bar
en/barn
en/barns
en/barometric
en/bearing
en/beaufort
en/because-paranoid
en/beep
en/beeperr
en/before-the-number
en/believe-its-free
en/billing
en/billing-and-collections
en/billionth
en/bits
en/blue-eyed-polar-bear
en/bookstore
en/boston
en/box
en/brian
en/business-development
en/busy-hangovers
en/busy-pls-hold
en/but
en/by
en/bytes
en/cafeteria
en/california
en/call
en/call-forward
en/call-forwarding
en/call-fwd-cancelled
en/call-fwd-no-ans
en/call-fwd-on-busy
en/call-fwd-parallel
en/call-fwd-unconditional
en/calling
en/call-preempted
en/call-quality-menu
en/call-requres
en/calls
en/calls-taken-by
en/calls-waiting-for-rep
en/call-terminated
en/call-waiting
en/campground-office
en/cancelled
en/cannot-complete-as-dialed
en/cannot-complete-network-error
en/cannot-complete-otherend-error
en/cannot-complete-temp-error
en/card-balance-is
en/card-is-invalid
en/card-number
en/carried-away-by-monkeys
en/cause-code
en/cc-amex
en/cc-discover
en/cc-mastercard
en/cc-visa
en/celsius
en/cent
en/central
en/cents
en/cents-per-minute
en/ceo-office
en/chance-of
en/changing
en/channel
en/channel-insecure-warn
en/channel-secure
en/charlotte
en/chat-room
en/check-number-dial-again
en/chemistry
en/chicago
en/chris
en/claims
en/clear
en/clearing
en/cleveland
en/clli
en/close-parenthesis
en/clouds
en/cloudy
en/collections
en/colorado
en/colorado-springs
en/columbus
en/comma
en/communications
en/company-dir-411
en/complaint
en/compliance
en/computer-friend1
en/computer-friend2
en/conditions
en/conf-adminmenu
en/conf-adminmenu-162
en/conf-banned
en/confbridge-join
en/confbridge-leave
en/conf-enteringno
en/conference
en/conference-call
en/conference-reservations
en/conf-errormenu
en/conf-extended
en/conf-full
en/conf-getchannel
en/conf-getconfno
en/conf-getpin
en/conf-hasentered
en/conf-hasjoin
en/conf-hasleft
en/conf-invalid
en/conf-invalidpin
en/confirm-number-is
en/conf-kicked
en/conf-leaderhasleft
en/conf-locked
en/conf-lockednow
en/conf-muted
en/conf-noempty
en/conf-nonextended
en/conf-now-muted
en/conf-now-recording
en/conf-now-unmuted
en/conf-onlyone
en/conf-onlyperson
en/conf-onlypersonleft
en/conf-otherinparty
en/conf-peopleinconf
en/conf-placeintoconf
en/conf-roll-callcomplete
en/conf-sysop
en/conf-sysopreq
en/conf-sysopreqcancelled
en/conf-thereare
en/conf-unlockednow
en/conf-unmuted
en/conf-usermenu
en/conf-usermenu-162
en/conf-userswilljoin
en/conf-userwilljoin
en/conf-waitforleader
en/conf-youareinconfnum
en/connected
en/connecticut
en/connecting
en/connection-failed
en/connection-timed-out
en/continue-english-press
en/continue-in-english
en/copy-center
en/could-lose-a-few-pounds
en/counseling-services
en/count
en/crash
en/currently
en/current-time-is
en/customer-accounts
en/customer-relations
en/customer-service
en/cyclone
en/dallas
en/date
en/day
en/daylight
en/days
en/de-activated
en/deadbeat
en/decode
en/default-attendant
en/degrees
en/delaware
en/demo-abouttotry
en/demo-congrats
en/demo-echodone
en/demo-echotest
en/demo-enterkeywords
en/demo-instruct
en/demo-moreinfo
en/demo-nogo
en/demo-nomatch
en/demo-thanks
en/denial-of-service
en/denver
en/department
en/department-administrator
en/deposit
en/descending-2tone
en/design
en/detroit
en/development
en/dial-here-often
en/digit
en/digits
en/directory
en/directory-assistance
en/dir-first
en/dir-firstlast
en/dir-instr
en/dir-intro
en/dir-intro-fn
en/dir-last
en/dir-multi1
en/dir-multi2
en/dir-multi3
en/dir-multi9
en/dir-nomatch
en/dir-nomore
en/dir-pls-enter
en/dir-usingkeypad
en/dir-welcome
en/disabled
en/disconnected
en/discon-or-out-of-service
en/disk
en/distribution
en/divided-by
en/dns
en/doing-enum-lookup
en/do-not-disturb
en/dont-know-who-sent
en/doppler-radar
en/down
en/driving-directions
en/duplex
en/duplication
en/early
en/east
en/easterly
en/eastern
en/echo-test
en/ed
en/eighteenth
en/eighth
en/eightieth
en/eleventh
en/el-paso
en/email
en/emergency
en/enabled
en/encode
en/engineering
en/enter-a-time
en/enter-conf-call-number
en/enter-conf-pin-number
en/enter-ext-of-person
en/entering-conf-number
en/enter-num-blacklist
en/enter-password
en/enter-phone-number10
en/entr-num-rmv-blklist
en/ent-target-attendant
en/enum-lookup-failed
en/enum-lookup-successful
en/error-number
en/est-hold-time-is
en/euro
en/european
en/euros
en/evening
en/explanation
en/extension
en/extensions
en/ext-or-zero
en/facilities
en/fahrenheit
en/falling
en/fast
en/feature-not-avail-line
en/feet
en/female
en/fifteenth
en/fifth
en/fiftieth
en/finals
en/finance
en/first
en/first-in-line
en/flagged-for-lea
en/flooding
en/florida
en/fog
en/foggy
en/followed-by
en/food-service
en/food-services
en/for
en/for-accounting
en/for-a-daily-wakeup-call
en/for-a-list-of
en/for-billing
en/for-english-press
en/for-investor-relations
en/for-louie-louie
en/for-no-press
en/for-qc-and-training-purposes
en/for-quality-purposes
en/for-sales
en/for-service
en/for-tech-support
en/for-the-first
en/for-the-weather
en/fortieth
en/fort-worth
en/for-wakeup-call
en/for-yes-press
en/fourteenth
en/fourth
en/freeze
en/freezing
en/frequency
en/fresno
en/from
en/from-unknown-caller
en/ftp
en/gale
en/gambling-drunk
en/georgia
en/gigabits
en/gigabytes
en/gigahertz
en/giggle1
en/gmt
en/go-away1
en/go-away2
en/good
en/good-afternoon
en/goodbye
en/good-evening
en/good-morning
en/greater-than
en/groovy
en/hail
en/half
en/hang-on-a-second
en/hang-on-a-second-angry
en/hangup-try-again
en/has
en/has-arrived-at
en/has-been
en/has-been-changed-to
en/has-been-cleared
en/has-been-disconnected
en/has-been-set-to
en/has-issued-a
en/has-not-been-seen-for
en/has-expired
en/hash
en/hawaii
en/headed-towards
en/heading
en/health-center
en/hear-odd-noise
en/hear-toilet-flush
en/hectopascal
en/hello
en/hello-world
en/helpdesk
en/hertz
en/high
en/highway
en/hit
en/hold-or-dial-0
en/home
en/honolulu
en/hours
en/housekeeping
en/houston
en/http
en/human-resources
en/humidity
en/hundredth
en/hurricane
en/hz
en/ice
en/icmp
en/icy
en/idaho
en/i-dont-understand
en/i-dont-understand2
en/i-dont-understand3
en/i-dont-understand4
en/i-dont-understand5
en/if-correct-press
en/if-grtg-played-indefinately
en/if-grtg-should-expire-at
en/if-maint-contract-or-emergency
en/if-rotary-phone
en/if-this-is-correct
en/if-this-is-correct-press
en/if-this-is-not-correct
en/if-u-know-ext-dial
en/if-unsuccessful-speak-to
en/if-youd-like-to-make-a-call
en/if-you-know-the
en/if-you-need-help
en/i-grow-bored
en/illinois
en/imap
en/im-sorry
en/im-sorry-unable-to-connect-to-eng
en/inbound
en/indiana
en/indianapolis
en/indicated
en/info-about-last-call
en/information
en/information-technology
en/infuriate-tech-staff
en/initiated
en/initiating
en/in-service
en/inside-sales
en/internal-audit
en/international-call
en/interstate
en/in-the
en/in-the-line
en/in-the-queue
en/invalid
en/invalid-date
en/invalid-featurecode
en/investor-relations
en/in-your-city
en/in-your-zip-code
en/iowa
en/is
en/is-at
en/is-curntly-busy
en/is-curntly-unavail
en/is-currently
en/is-in-use
en/is-not-in-the
en/is-not-set
en/is-now-being-recorded
en/is-set-to
en/it-now
en/it-services
en/jacksonville
en/janitorial
en/jason
en/jedi-extension-trick
en/john
en/just-kidding-not-upset
en/just-kidding-not-upset2
en/kansas
en/kansas-city
en/kentucky
en/kilobits
en/kilobytes
en/kilohertz
en/kilometer
en/kilometers-per-hour
en/knock-knock
en/knots
en/language
en/last-error-was
en/last-num-to-call
en/las-vegas
en/late
en/later
en/lea-may-request-info
en/left-bracket
en/legal
en/len
en/less-than
en/library
en/lightning
en/limit-simul-calls
en/lines-complaining-customers
en/linux
en/list
en/load-average
en/local-authorities
en/location
en/login-fail
en/long-beach
en/los-angeles
en/loss
en/loss-prevention
en/lots-o-monkeys
en/louisiana
en/low
en/lunch
en/lyrics-louie-louie
en/machine
en/made-it-up
en/mail
en/mailroom
en/maine
en/main-menu
en/maintenance
en/male
en/management
en/manufacturing
en/marketing
en/marryme
en/maryland
en/massachusetts
en/mathematics
en/maximum
en/megabits
en/megabytes
en/megahertz
en/memory
en/memphis
en/menu
en/mesa
en/message-from
en/message-number
en/meter
en/meters
en/miami
en/michigan
en/midnight
en/midnight-tomorrow-night
en/midnight-tonight
en/mike
en/miles
en/miles-per-hour
en/millionth
en/milwaukee
en/minimum
en/minneapolis
en/minnesota
en/minute
en/minutes
en/missed
en/mississippi
en/missouri
en/misty
en/monitored
en/montana
en/month
en/months
en/moo1
en/moo2
en/morning
en/moron
en/mostly
en/motor-pool
en/mountain
en/moving
en/ms
en/nashville
en/national-weather-service
en/nautical-miles
en/nbdy-avail-to-take-call
en/near
en/nebraska
en/negative
en/network-operations
en/network-operations-center
en/nevada
en/new-accounts
en/new-hampshire
en/new-jersey
en/new-mexico
en/new-orleans
en/new-york
en/nineteenth
en/ninetieth
en/ninth
en/no-112-1
en/no-112-2
en/no-911-1
en/no-911-2
en/nobody-but-chickens
en/node
en/no-empty-conferences
en/no-info-about-number
en/no-longer-in-service
en/no-reply-no-mailbox
en/no-route-exists-to-dest
en/north
en/north-carolina
en/north-dakota
en/northerly
en/not-auth-pstn
en/not-enough-credit
en/nothing-recorded
en/not-necessary-1
en/not-necessary-ac
en/not-necessary-dial-1-or-ac
en/not-rqsted-wakeup
en/not-taking-your-call
en/not-yet-assigned
en/not-yet-connected
en/now
en/number
en/number-not-answering
en/num-not-in-db
en/num-outside-area
en/num-was-successfully
en/oakland
en/octothorpe
en/off-duty
en/office
en/office-code
en/office-iguanas
en/ohio
en/oklahoma
en/oklahoma-city
en/omaha
en/on
en/on-busy
en/one-moment-please
en/one-small-step
en/one-small-step2
en/on-monthly-tel-stment
en/on-no-answer
en/oops1
en/oops2
en/oops3
en/open-parenthesis
en/operations
en/option-is-invalid
en/option-not-implemented
en/or
en/order-desk
en/orders
en/oregon
en/or-press
en/other-options-exercise
en/otherwise
en/otherwise-press
en/our-business-hours-are
en/outbound
en/outside-sales
en/outside-transfer
en/pacific
en/packet
en/panic
en/partially
en/partly
en/pascal
en/pascal2
en/patchy
en/pbx-invalid
en/pbx-invalidpark
en/pbx-parkingfailed
en/pbx-transfer
en/pence
en/pennies
en/pennsylvania
en/penny
en/percent
en/perhaps-we-are
en/perhaps-we-are2
en/period
en/personnel
en/persons-in-path-of
en/philadelphia
en/phoenix
en/physics
en/ping
en/pin-invalid
en/pin-number-accepted
en/pipe
en/planning
en/please-answer-the-following
en/please-contact-tech-supt
en/please-enter-first-three-letters
en/please-enter-the
en/please-enter-your
en/please-hang-up-and-dial-operator
en/please-hang-up-and-try-again
en/please-try
en/please-try-again
en/please-try-again-later
en/please-wait-connect-oncall-eng
en/pls-enter-conf-password
en/pls-enter-num-message-after-tone
en/pls-enter-vm-password
en/pls-ent-num-transfer
en/pls-entr-num-uwish2-call
en/pls-hold-process-tx
en/pls-hold-silent30
en/pls-hold-while-try
en/pls-lv-msg-will-contact
en/pls-rcrd-name-at-tone
en/pls-stay-on-line
en/pls-try-again
en/pls-try-area-code
en/pls-try-call-later
en/pls-try-manually
en/pls-wait-connect-call
en/plugh
en/pm-announcement-number
en/pm-invalid-option
en/pm-phrase-management
en/pm-prompt-number
en/pm-to-record-phrase
en/pm-to-review-phrase
en/point
en/pop
en/port
en/portland
en/portnumber
en/position
en/post-entry-pound
en/pounds
en/presales-support
en/presidents-office
en/press
en/press-0
en/press-1
en/press-2
en/press-3
en/press-4
en/press-5
en/press-6
en/press-6-to-eject
en/press-7
en/press-8
en/press-9
en/press-button-again
en/press-enter
en/press-escape
en/press-hash
en/press-pound
en/press-pound-save-changes
en/press-pound-to-login-star-to-hangup
en/press-return
en/press-star
en/press-star-cancel
en/press-the-space-bar
en/press-tilde
en/pressure
en/printing
en/privacy-blacklisted
en/privacy-blocked
en/privacy-if-error
en/privacy-if-error-leave-message-or-hangup
en/privacy-if-sales-call-contact-in-writing
en/privacy-incorrect
en/privacy-last-caller-was
en/privacy-not
en/privacy-please-dial
en/privacy-please-stay-on-line-to-be-connected
en/privacy-prompt
en/privacy-restricted-by-req
en/privacy-screening-unidentified-calls
en/privacy-stop-calling-not-welcome
en/privacy-stop-calling-not-welcome2
en/privacy-thankyou
en/privacy-this-number-is
en/privacy-to-blacklist-last-caller
en/privacy-to-blacklist-this-number
en/privacy-to-hear-our-contact-details
en/privacy-to-whitelist-last-caller
en/privacy-to-whitelist-this-number
en/privacy-unident
en/privacy-whitelisted
en/privacy-you-are-blacklisted
en/privacy-you-are-calling-from
en/privacy-your-callerid-is
en/priv-callee-options
en/priv-callpending
en/priv-introsaved
en/priv-recordintro
en/product
en/production
en/projects
en/protocol
en/public-relations
en/purchasing
en/purposes
en/q-dot-931
en/q-dot-9thirty1
en/quality-assurance
en/quality-control
en/quarter
en/queue-callswaiting
en/queue-holdtime
en/queue-less-than
en/queue-minute
en/queue-minutes
en/queue-periodic-announce
en/queue-quantity1
en/queue-quantity2
en/queue-reporthold
en/queue-seconds
en/queue-thankyou
en/queue-thereare
en/queue-youarenext
en/quickly
en/quote
en/race
en/rain
en/rainfall
en/rainy
en/range
en/reassigned-new-areacode
en/rebates
en/received
en/receiving
en/reception
en/recorded
en/registrar
en/remote-already-in-this-mode
en/remote-already-in-this-mode-2
en/remote-base
en/removed
en/repair
en/repeater
en/repeat-only
en/research
en/research-and-development
en/reservations
en/restarting
en/rhode-island
en/right-bracket
en/rising
en/risk-management
en/roaming
en/room-service
en/route-sip
en/rqsted-wakeup-for
en/sacramento
en/saint-louis
en/sales
en/sales-floor
en/san-antonio
en/san-diego
en/san-francisco
en/san-jose
en/save-announce-press
en/says-thats-stupid
en/say-temp-msg-prs-pound
en/scattered
en/sciences
en/screen-callee-options
en/seattle
en/second
en/seconds
en/secretary
en/security
en/self-destruct
en/self-destruct-in
en/server
en/service
en/service-not-implemented
en/seventeenth
en/seventh
en/seventieth
en/severe
en/shall-i-try-again
en/shiny-brass-lamp
en/shipping
en/shop
en/show-office
en/sighted
en/simplex
en/simul-call-limit-reached
en/sixteenth
en/sixth
en/sixtieth
en/sleet
en/sleeting
en/slow
en/slowly
en/snow
en/snowing
en/snowy
en/software
en/someone-you-trust1
en/someone-you-trust2
en/someone-you-trust3
en/something-terribly-wrong
en/sorry
en/sorry2
en/sorry-cant-let-you-do-that
en/sorry-cant-let-you-do-that2
en/sorry-cant-let-you-do-that3
en/sorry-mailbox-full
en/sorry-youre-having-problems
en/south
en/south-carolina
en/south-dakota
en/southerly
en/spam
en/spam2
en/speak-louder
en/speak-louder-into-phone
en/speak-to-the-operator
en/speed
en/speed-dial
en/speed-dial-empty
en/splat
en/spy-agent
en/spy-console
en/spy-dahdi
en/spy-h323
en/spy-iax
en/spy-iax2
en/spy-jingle
en/spy-local
en/spy-mgcp
en/spy-misdn
en/spy-mobile
en/spy-nbs
en/spy-sip
en/spy-skinny
en/spy-unistim
en/spy-usbradio
en/spy-zap
en/ssh
en/ss-noservice
en/staff
en/staffing
en/standard
en/star-for-menu-again
en/starting-with-either
en/station
en/status
en/step-in-stream
en/sterling
en/store-accounting
en/storm
en/sun
en/sunny
en/support
en/swap
en/system
en/system-crashed
en/systems
en/system-status-msg
en/talking-to-myself
en/target-attendant
en/T-changed-to
en/tcp
en/technical-support
en/telephone-in-your-pocket
en/telephone-in-your-pocket2
en/telephone-number
en/telesales
en/teletubbie-murder
en/telnet
en/temp-disconnected
en/temperature
en/tennessee
en/tenth
en/terabits
en/terabytes
en/terminated
en/terminating
en/test-tones-follow
en/texas
en/thanks-for-calling-today
en/thanks-for-using
en/thank-you-cooperation
en/thank-you-for-calling
en/that-is-not-rec-phn-num
en/that-number
en/that-tickles
en/that-you-require
en/the-mailbox
en/the-monkeys-twice
en/the-new-number-is
en/the-next
en/then-press-pound
en/the-number-u-dialed
en/the-num-i-have-is
en/the-party-you-are-calling
en/there-are
en/there-is-no-customer-support
en/these-are-currently
en/the-weather-at
en/third
en/thirteenth
en/thirtieth
en/this
en/this-call-may-be
en/this-call-may-be-monitored-or-recorded
en/this-call-will-cost
en/this-call-will-end-in
en/this-is-the-voice-mail-system
en/this-is-yr-wakeup-call
en/thnk-u-for-patience
en/thousandth
en/through
en/thunderstorm
en/tide
en/time
en/times
en/T-is-not-available
en/to-accept-recording
en/to-be-called-back
en/to-blklist-last-caller
en/to-blklist-last-num
en/to-call-num-press
en/to-call-prson-w-sent-msg
en/to-call-this-number
en/to-cancel-this-msg
en/to-cancel-wakeup
en/to-change-exp-date
en/to-change-your-pin-number
en/to-collect-voicemail
en/to-compose-a-message
en/to-confirm-wakeup
en/to-dial-by-name
en/to-dial-by-name-press
en/to-enter-a-diff-number
en/to-enter-a-number
en/to-erase-yr-temp-grtg
en/to-extension
en/to-hang-up
en/to-hang-up-2
en/to-hear-callerid
en/to-hear-menu-again
en/to-hear-msg-again
en/to-hear-msg-envelope
en/to-hear-net-status
en/to-hear-weather-status
en/to-hear-your-account-balance
en/to-join-a-meeting
en/to-leave-message-for
en/to-listen-to-it
en/to-log-in-to-voice-mail
en/tomorrow-night
en/tones-that-follow-are-for-the-deaf
en/tonight
en/too-low
en/to-place-outgoing-call
en/to-reach-first-rep
en/to-reach-operator
en/to-record-call
en/to-rec-yr-temp-grtg
en/to-redial-the-last-number-you-called
en/to-report-emergency
en/to-report-system-network-down
en/to-rerecord-announce
en/to-rerecord-it
en/to-rerecord-yr-message
en/to-rmv-num-blklist
en/tornado
en/to-rqst-wakeup-call
en/to-send-a-reply
en/to-snooze-for
en/touchtone1
en/touchtone2
en/touchtone3
en/to-use-def-attendant
en/towards
en/trading-desk
en/traffic
en/training
en/transfer
en/transportation
en/travel
en/treasury
en/tt-allbusy
en/tt-codezone
en/tt-codezone_MIXDOWN
en/tt-hangup
en/tt-monkeys
en/tt-monkeysintro
en/tt-monty-knights
en/T-to-disable-ancmnt
en/T-to-enable-ancmnt
en/T-to-hear-cur-ancmnt
en/T-to-leave-msg
en/T-to-reach-main-office
en/T-to-rec-ancmnt
en/T-to-rtrn-to-main-menu
en/tt-somethingwrong
en/tt-weasels
en/tucson
en/tulsa
en/turning-to
en/turn-off-recording
en/twelveth
en/twentieth
en/twisty-maze
en/tx-has-been-approved
en/typhoon
en/udp
en/uh-oh1
en/uh-oh2
en/uk
en/unavailable
en/unconditional
en/unidentified-no-callback
en/units
en/unix
en/up
en/uptime
en/user
en/users
en/utah
en/variable
en/vermont
en/virginia
en/virginia-beach
en/visibility
en/visit-asterisk-website
en/vm-advopts
en/vm-and
en/vm-calldiffnum
en/vm-changeto
en/vm-Cust1
en/vm-Cust2
en/vm-Cust3
en/vm-Cust4
en/vm-Cust5
en/vm-delete
en/vm-deleted
en/vm-dialout
en/vm-duration
en/vm-enter-num-to-call
en/vm-extension
en/vm-Family
en/vm-first
en/vm-for
en/vm-forward
en/vm-forward-multiple
en/vm-forwardoptions
en/vm-Friends
en/vm-from
en/vm-from-extension
en/vm-from-phonenumber
en/vm-goodbye
en/vm-helpexit
en/vm-INBOX
en/vm-incorrect
en/vm-incorrect-mailbox
en/vm-instructions
en/vm-intro
en/vm-invalidpassword
en/vm-invalid-password
en/vm-isonphone
en/vm-isunavail
en/vm-last
en/vm-leavemsg
en/vm-login
en/vm-mailboxfull
en/vm-marked-nonurgent
en/vm-marked-urgent
en/vm-message
en/vm-messages
en/vm-minutes
en/vm-mismatch
en/vm-msginstruct
en/vm-msgsaved
en/vm-newpassword
en/vm-newuser
en/vm-next
en/vm-no
en/vm-nobodyavail
en/vm-nobox
en/vm-nomore
en/vm-nonumber
en/vm-num-i-have
en/vm-Old
en/vm-onefor
en/vm-onefor-full
en/vm-options
en/vm-opts
en/vm-opts-full
en/vm-passchanged
en/vm-password
en/vm-pls-try-again
en/vm-press
en/vm-prev
en/vm-reachoper
en/vm-rec-busy
en/vm-received
en/vm-rec-name
en/vm-record-prepend
en/vm-rec-temp
en/vm-rec-unv
en/vm-reenterpassword
en/vm-repeat
en/vm-review
en/vm-review-nonurgent
en/vm-review-urgent
en/vm-saved
en/vm-savedto
en/vm-savefolder
en/vm-savemessage
en/vm-saveoper
en/vm-sorry
en/vm-star-cancel
en/vm-starmain
en/vm-tempgreetactive
en/vm-tempgreeting
en/vm-tempgreeting2
en/vm-tempremoved
en/vm-then-pound
en/vm-theperson
en/vm-tmpexists
en/vm-tocallback
en/vm-tocallnum
en/vm-tocancel
en/vm-tocancelmsg
en/vm-toenternumber
en/vm-toforward
en/vm-tohearenv
en/vm-tomakecall
en/vm-tooshort
en/vm-toreply
en/vm-torerecord
en/vm-undelete
en/vm-undeleted
en/vm-unknown-caller
en/vm-Urgent
en/vm-whichbox
en/vm-Work
en/vm-youhave
en/voice-mail-system
en/wait-moment
en/wait-offensive-sounds
en/wakeup-call
en/wakeup-call-cancelled
en/wakeup-daily
en/wakeup-for-daily
en/wakeup-for-one-time
en/wakeup-onetime
en/walks-into-bar-mail
en/warning
en/was
en/washington
en/washington-dc
en/was-last-seen
en/watch
en/we-apologize
en/weasels-eaten-phonesys
en/weather
en/weather-station
en/web
en/we-dont-have-tech-support
en/weeks
en/welcome
en/were-sorry
en/west
en/westerly
en/west-virginia
en/what-are-you-wearing
en/what-time-it-is
en/what-time-it-is2
en/when-dialing-this-number
en/who-would-you-like-to-call
en/why-no-answer-mystery
en/wichita
en/will-apply
en/will-expire
en/will-not-expire
en/will-reflect-charge-of
en/wind
en/windows
en/windy
en/wisconsin
en/wish-to-continue
en/with
en/within
en/work
en/wrong-try-again-smarty
en/wtng-to-spk-w-rep
en/www-switchboard-com
en/wyoming
en/yeah
en/year
en/years
en/yes-dear
en/yes-dear2
en/you-are-caller-num
en/you-are-curr-call-num
en/you-can-press
en/you-dialed-wrong-number
en/you-entered
en/you-have-dialed
en/you-have-reached-a-test-number
en/you-have-these-options
en/you-must-first-dial
en/your
en/your-account
en/your-msg-has-been-saved
en/your-msg-is-too-short
en/your-notifications
en/your-req-notification
en/your-temp-greeting
en/you-seem-impatient
en/you-sound-cute
en/you-wish-to-join
en/zip-code
osdial/,
osdial/buzz
osdial/conf
osdial/ding
osdial/dtmf-0
osdial/dtmf-1
osdial/dtmf-2
osdial/dtmf-3
osdial/dtmf-4
osdial/dtmf-5
osdial/dtmf-6
osdial/dtmf-7
osdial/dtmf-8
osdial/dtmf-9
osdial/dtmf-hash
osdial/dtmf-star
osdial/enter
osdial/four_digit_id
osdial/generic_hold
osdial/hold_tone
osdial/invalid-extension
osdial/invalid-room
osdial/ld_invalid_pin_number
osdial/ld_welcome_pin_number
osdial/leave
osdial/park
osdial/please-enter-the-extension-2-b-monitored
osdial/please-enter-the-room-number-you-wish-to-join
osdial/silence
osdial/sip-silence
osdial/vm-rec-generic
