--- #YAML:1.0
name:               OSDial
version:            SVN_Version
abstract:           Perl module for interfacing with the OSDial. 
author:
    - Lott Caskey <lottcaskey@gmail.com>
license:            AGPLv2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:                  0
    Asterisk::AGI:        0
    Digest::MD5:          0
no_index:
    directory:
        - t
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
